### ISSUE TITLE
OC 3.0

### ISSUE THREAD

**Issue by khamyee** [nmzaw/mpu_oc#1]
Hello, I would like to ask whether you have the new version for OC 3.0? If not will you be able to do the upgrade of the version with a service fees? I can't seem to find a way to contact you and please call me at 09421175990 for the discussion. Hope to hear something from you. :)

**Comment by nmzaw** [comment]
Sorry about late reply, I don't used any more for OC. So, I couldn't upgrade to fit with 3.0. Thanks for understanding to me.
